export const ADDITIONAL_THEMES = `
  "neon-cyber": {
    label: "Neon Cyber",
    createdAt: "2026-03-11",
    styles: {
      light: {
        background: "#fdfcff",
        foreground: "#0d0221",
        card: "#ffffff",
        "card-foreground": "#0d0221",
        popover: "#ffffff",
        "popover-foreground": "#0d0221",
        primary: "#00e5ff",
        "primary-foreground": "#001015",
        secondary: "#f1ecff",
        "secondary-foreground": "#1a0a3e",
        muted: "#f4f3ff",
        "muted-foreground": "#6b6392",
        accent: "#ff2afc",
        "accent-foreground": "#ffffff",
        destructive: "#ff4b6e",
        "destructive-foreground": "#ffffff",
        border: "#e8e5ff",
        input: "#eceaff",
        ring: "#00e5ff",
        "chart-1": "#00e5ff",
        "chart-2": "#ff2afc",
        "chart-3": "#39ff14",
        "chart-4": "#ffe600",
        "chart-5": "#ff6a00",
        sidebar: "#f6f4ff",
        "sidebar-foreground": "#0d0221",
        "sidebar-primary": "#00e5ff",
        "sidebar-primary-foreground": "#001015",
        "sidebar-accent": "#eceaff",
        "sidebar-accent-foreground": "#1a0a3e",
        "sidebar-border": "#eceaff",
        "sidebar-ring": "#00e5ff",
        "font-sans": "Plus Jakarta Sans, sans-serif",
        "font-serif": "Lora, serif",
        "font-mono": "IBM Plex Mono, monospace",
        radius: "1.4rem",
        "shadow-color": "hsl(265 100% 30%)",
        "shadow-opacity": "0.2",
        "shadow-blur": "8px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "3px",
        "letter-spacing": "-0.025em",
        spacing: "0.27rem",
      },

      dark: {
        background: "#0d0221",
        foreground: "#e9e6ff",
        card: "#140533",
        "card-foreground": "#e9e6ff",
        popover: "#140533",
        "popover-foreground": "#e9e6ff",
        primary: "#00e5ff",
        "primary-foreground": "#001015",
        secondary: "#1a0a3e",
        "secondary-foreground": "#dcd6ff",
        muted: "#1a0a3e",
        "muted-foreground": "#7c6f9f",
        accent: "#ff2afc",
        "accent-foreground": "#ffffff",
        destructive: "#ff4b6e",
        "destructive-foreground": "#ffffff",
        border: "#2d1b69",
        input: "#2d1b69",
        ring: "#00e5ff",
        "chart-1": "#00e5ff",
        "chart-2": "#ff2afc",
        "chart-3": "#39ff14",
        "chart-4": "#ffe600",
        "chart-5": "#ff6a00",
        sidebar: "#090019",
        "sidebar-foreground": "#e9e6ff",
        "sidebar-primary": "#00e5ff",
        "sidebar-primary-foreground": "#001015",
        "sidebar-accent": "#1a0a3e",
        "sidebar-accent-foreground": "#00e5ff",
        "sidebar-border": "#2d1b69",
        "sidebar-ring": "#00e5ff",
        "font-sans": "Plus Jakarta Sans, sans-serif",
        "font-serif": "Lora, serif",
        "font-mono": "IBM Plex Mono, monospace",
        radius: "1.4rem",
        "shadow-color": "hsl(190 100% 50%)",
        "shadow-opacity": "0.35",
        "shadow-blur": "12px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "4px",
        "letter-spacing": "-0.025em",
        spacing: "0.27rem",
      },
    },
  },

  "deep-space": {
    label: "Deep Space",
    createdAt: "2026-08-31",
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#0b0a18",
        card: "#ffffff",
        "card-foreground": "#0b0a18",
        popover: "#ffffff",
        "popover-foreground": "#0b0a18",
        primary: "#4d30ff",
        "primary-foreground": "#ffffff",
        secondary: "#f1edff",
        "secondary-foreground": "#312570",
        muted: "#f5f3fb",
        "muted-foreground": "#5b5670",
        accent: "#f4e9ff",
        "accent-foreground": "#7a2fd6",
        destructive: "#e5484d",
        "destructive-foreground": "#ffffff",
        border: "#e6e1f5",
        input: "#e6e1f5",
        ring: "#4d30ff",
        "chart-1": "#4d30ff",
        "chart-2": "#6c46ff",
        "chart-3": "#925bff",
        "chart-4": "#b36dfb",
        "chart-5": "#cb7cfd",
        sidebar: "#faf9ff",
        "sidebar-foreground": "#0b0a18",
        "sidebar-primary": "#4d30ff",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#f4e9ff",
        "sidebar-accent-foreground": "#7a2fd6",
        "sidebar-border": "#e6e1f5",
        "sidebar-ring": "#4d30ff",
        "font-sans": "Inter, sans-serif",
        "font-serif": "Merriweather, serif",
        "font-mono": "JetBrains Mono, monospace",
        radius: "0.75rem",
        "shadow-color": "hsl(252 100% 60%)",
        "shadow-opacity": "0.12",
        "shadow-blur": "16px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "4px",
        "letter-spacing": "-0.01em",
      },
      dark: {
        background: "#020107",
        foreground: "#ffffff",
        card: "#0b0a18",
        "card-foreground": "#ffffff",
        popover: "#0b0a18",
        "popover-foreground": "#ffffff",
        primary: "#4d30ff",
        "primary-foreground": "#ffffff",
        secondary: "#14121f",
        "secondary-foreground": "#e4e1f0",
        muted: "#0f0e1a",
        "muted-foreground": "#8b88a3",
        accent: "#1a1330",
        "accent-foreground": "#cb7cfd",
        destructive: "#ff5d6c",
        "destructive-foreground": "#020107",
        border: "rgba(77, 48, 255, 0.38)",
        input: "rgba(77, 48, 255, 0.38)",
        ring: "#4d30ff",
        "chart-1": "#4d30ff",
        "chart-2": "#6b4aff",
        "chart-3": "#8f63ff",
        "chart-4": "#b36dfb",
        "chart-5": "#cb7cfd",
        sidebar: "#060512",
        "sidebar-foreground": "#ffffff",
        "sidebar-primary": "#4d30ff",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "rgba(77, 48, 255, 0.12)",
        "sidebar-accent-foreground": "#ffffff",
        "sidebar-border": "rgba(77, 48, 255, 0.38)",
        "sidebar-ring": "#4d30ff",
        "font-sans": "Inter, sans-serif",
        "font-serif": "Merriweather, serif",
        "font-mono": "JetBrains Mono, monospace",
        radius: "0.75rem",
        "shadow-color": "hsl(252 100% 60%)",
        "shadow-opacity": "0.35",
        "shadow-blur": "24px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "8px",
        "letter-spacing": "-0.01em",
      },
    },
  },
`;
